site_name: UIT Document
docs_dir: source
nav:
  - Home: index.md
  # - Good Read: goodread.md
  # - Vignettes: vignette.md
  # - Editorials: editorials.md
  # - Technicals: technical.md
  # - About: about.md
theme:
  name: material
  favicon: images/UIT-logo.png
  # logo: images/UIT-logo.png
  features:
    - navigation.footer
    - navigation.instant
    - header.autohide
    - navigation.tabs
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      
plugins:
  - tags
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
extra:
  homepage: https://sonnh-uit.github.io/UIT_document
copyright: Copyright &copy; 2023 - Son Nguyen-Hong